[package]
name = "random-string"
version = "0.1.0"
authors = ["FssAy <49795742+DmitrijVC@users.noreply.github.com>"]
edition = "2018"
license = "GNU General Public License v3.0"
description = "Allows to generate random strings based on a given charset and length."
# documentation = "-"
repository = "https://github.com/DmitrijVC/random-string"
readme = "README.md"

[dependencies]
random-number = "0.1.3"
